// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpnsnvfsnuvgbdtkpbkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbnNudmZzbnV2Z2JkdGtwYmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQ4MjQsImV4cCI6MjA2NTU2MDgyNH0.IbSATqiA1iq4SUsO4F2D7T8PPV503edCKCnBRd9MPPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);